### ISSUE TITLE
绑定界面的回调地址

### ISSUE THREAD

**Issue by essesoul** [imeepo/flarum-auth-qq#1]
绑定界面的回调地址好像应该是  `域名/api//auth/qq/link` ，qq互联不加的话点击会有redirect uri is illegal(100010)错误
api后面有两个斜杠的问题是之前作者留下的，大佬能修一下吗

**Comment by imeepo** [comment]
我自己绑定那里可以用的，你别加/api试试，你看看我上边的说明，在网站回调域那里加上绑定链接，分号隔开。

网站地址：https://你的域名/
网站回调域：https://你的域名/auth/qq;https://你的域名/api/auth/qq/link

**Comment by essesoul** [comment]
我试了一下，不添加的话绑定页面会有报错，但是api后面两个斜杠应该没什么影响，回调还是要写`域名/api/auth/qq/link`才有效

**Comment by imeepo** [comment]
我看了下，我的QQ互联那里link链接确实是加着api的，整理文档的时候可能没注意，我已经修改了文档。

然后我也复现了你说多一个斜杠的问题，并修复了它，你可以用`composer update imeepo/flarum-auth-qq`来更新扩展到`v1.0.3`版本
